[build]
    publish = "src"
[[redirects]]
    from = "/github"
    to = "https://github.com/andrejarrell"
[[redirects]]
    from = "/listcord"
    to = "https://listcord.net"
[[redirects]]
    from = "/glitch"
    to = "https://glitch.com/@andrejarrell"
[[redirects]]
    from = "/pay"
    to = "https://www.paypal.com/paypalme/andrejarrell"
[[redirects]]
    from = "/*"
    to = "/404"
    status = 404