[build]
    publish = "src"
[[redirects]]
    from = "/*"
    to = "https://github.com/andrejarrell"
[[redirects]]
    from = "/github"
    to = "https://github.com/andrejarrell"
[[redirects]]
    from = "/dev"
    to = "https://dev.to/andrejarrell"
[[redirects]]
    from = "/glitch"
    to = "https://glitch.com/@andrejarrell"
[[redirects]]
    from = "/paypal"
    to = "https://www.paypal.com/paypalme/andrejarrell"
[[redirects]]
    from = "/cashapp"
    to = "https://cash.app/$andredjarrell"
[[redirects]]
    from = "/venmo"
    to = "https://venmo.com/u/andrejarrell"
[[redirects]]
    from = "/disney"
    to = "https://gist.github.com/andrejarrell/4b25a6c863eecf6b97ffcc539f8b2cc4#file-disney-md"